### ISSUE TITLE
uri not in RDF namespace

### ISSUE THREAD

**Issue by rmfranken** [CSIRO-enviro-informatics/shacl-form#2]
Hello there, 

I'm trying to use this piece of software (and if it's somewhat usable, maybe contribute to it also), but am running into some trouble just trying to get the example to run. I fear it may have something to do with rdflib, as the error I'm receiving references a call to RDF.uri. 

`C:\Users\franken\shacl-form\venv\Scripts\python.exe C:\Users\franken\shacl-form\app.py 
 * Serving Flask app 'app'
 * Debug mode: on
Traceback (most recent call last):
  File "C:\Users\franken\shacl-form\venv\Lib\site-packages\flask\app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\franken\shacl-form\venv\Lib\site-packages\flask\app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\franken\shacl-form\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\franken\shacl-form\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\franken\shacl-form\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\franken\shacl-form\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\franken\shacl-form\controller\routes.py", line 24, in gen_form
    generate_form(shape, form_destination=form_filepath, map_destination=map_filepath)
  File "C:\Users\franken\shacl-form\shaclform\generate_form.py", line 18, in generate_form
    shape = rdf_handler.get_shape()
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\franken\shacl-form\shaclform\rdfhandling\__init__.py", line 43, in get_shape
    shape_uris = list(self.g.subjects(URIRef(RDF.uri + 'type'), URIRef(SHACL + 'NodeShape')))
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\franken\shacl-form\venv\Lib\site-packages\rdflib\namespace\__init__.py", line 239, in __getattr__
    return cls.__getitem__(name)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\franken\shacl-form\venv\Lib\site-packages\rdflib\namespace\__init__.py", line 230, in __getitem__
    raise AttributeError(f"term '{name}' not in namespace '{cls._NS}'")
AttributeError: term 'uri' not in namespace 'http://www.w3.org/1999/02/22-rdf-syntax-ns#'
` 

Is this app still being monitored? I see the last commit is ~5 years old, but I figured I would try anyway since the functionality described in the readMe is exactly what I'm looking for!

**Comment by dr-shorthair** [comment]
@ashleysommer @nicholascar ??

**Comment by rmfranken** [comment]
Guess not? :( I will move forward with trying to figure out schimatos, which I think has a similar mission. Regardless I will continue to follow this repository just in case there is still movement in it :)
